### ISSUE TITLE
Email speakers with time slots/rooms

### ISSUE THREAD

**Issue by lynnaloo** [RevolutionConf/Organization#102]
- Email with final details to speakers
- Get information for introduction

**Comment by erikpmp** [comment]
How about we send this out now? Good enough?

![screen shot 2016-04-23 at 6 52 44 am](https://cloud.githubusercontent.com/assets/1593872/14760962/07e445ae-0920-11e6-9dec-97cd61470502.png)

**Comment by lynnaloo** [comment]
I have an email ready now to go with this to speakers first (to see if they
need changes before we publicize). I was late drafting it up, but it's
waiting some polish from Kevin before it goes out.
