### ISSUE TITLE
What happens if a speaker is a no-show?

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#113]
Cancel the session?

Someone to fill in?

Do we want to invite any of the alternates and have them be ready to talk? (probably not)

**Comment by lynnaloo** [comment]
Unless someone from the staff has a talk they can give on demand, it might be better to just cancel.

**Comment by erikpmp** [comment]
Agreed, and I think @1kevgriff previously mentioned he felt the same way. I'll close this issue.
