### ISSUE TITLE
Put in final t-shirt order

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#123]

**Comment by erikpmp** [comment]
@1kevgriff is going to tweak the numbers in the budget this weekend.
https://docs.google.com/spreadsheets/d/1a9aVGH9oxvKEDYKYsHAFTaW730FO2OM70wGdJr4f3Ww/edit#gid=1763344901

@1kevgriff When you're done, please send the final numbers to @metaskills and then this issue can be closed.

**Comment by metaskills** [comment]
Thanks y'all. Looking forward to helping out more toward the end here. Thanks again for letting me be part of this.

**Comment by erikpmp** [comment]
Done. This was submitted to Custom Ink yesterday. ETA on shirts is 5/9/2016.
