### ISSUE TITLE
Send email reminders - 1 week before

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#124]
Include...

Email ticket holders to transfer tickets (if necessary) prior to the day of the event #144

**Comment by erikpmp** [comment]
@1kevgriff As our "email guy", I assume you'll be taking care of this.?

**Comment by erikpmp** [comment]
Changing this to be the one email notification that we'll send to all attendees within a week of the event. This should be the last notification we send.

**Comment by 1kevgriff** [comment]
Overshot this - will just send 2 day notice.
