### ISSUE TITLE
Create sign-in sheets/system

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#134]

**Comment by lynnaloo** [comment]
What is this for? Attendees or volunteers?

**Comment by erikpmp** [comment]
For attendees. Do we want to track who actually attended? Or maybe we'll just do it by whichever name badges are left over (preferred).

**Comment by lynnaloo** [comment]
I think the room monitors can do a head count per room just to get an idea of who attended what, but yeah the name badges will tell us who didn't show.
