### ISSUE TITLE
Sponsorship Packages

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Organization#14]
$$$

Nice to Haves:
- [ ] Night before Happy Hour at Shorebreak
- [ ] Happy hour on the deck after the event
- [ ] Keynote Speaker (speaking fee/travel)

**Comment by seanmerron** [comment]
Food Sponsor
T-Shirt Sponsor
Swag Sponsor
have also seen where all sponsors are required to bring a swag raffle

**Comment by erikpmp** [comment]
@1kevgriff and @lynnaloo Can you draft a sponsor package?

**Comment by erikpmp** [comment]
sponsorship packages are done and in the budget spreadsheet
