### ISSUE TITLE
Announce Keynote Speaker

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Organization#17]

**Comment by guillermoandrae** [comment]
Put feelers out for Gina Trapani, haven't heard anything back yet. Will push more after the new year.

**Comment by switchspan** [comment]
@lynnaloo , @metaskills , and @guillermoandrae -> Moving the short list here from the previously closed issue:

1) Randall Munroe (@lynnaloo investigating)
2) Leland Melvin (@lynnaloo investigating)
3) Sara Chipps (@lynnaloo will contact)
4) Andy Hunt (@metaskills confirmed available)
5) Sandi Metz
6) Gina Trapani (@guillermoandrae investigating)
7) Corey Haines (@switchspan investigating)

**Comment by guillermoandrae** [comment]
I heard back from my Gina Trapani contact and I need a few lines to send about the conference. Do we have anything already written up?

**Comment by metaskills** [comment]
Happy new year y'all. Just got done with a few busy off/on weeks. Here if you need me.

**Comment by lynnaloo** [comment]
@1kevgriff Is this closed by posting on the website/twitter?

**Comment by 1kevgriff** [comment]
BOOM! :boom:
