### ISSUE TITLE
Printed Material / Stickers

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Organization#18]
* [x] Stickers
* [ ] For attendees. Ex: a printed 1/3 page cardstock flyer
* [ ] For businesses. Ex: a printed 1/3 page cardstock flyer with a primary goal of getting the business's developers to attend, and secondary goal of getting the business to sponsor in order to get their developers in for less.
* [ ] For sponsorship. Ex: table format showing levels, pricing, and what they get

**Comment by erikpmp** [comment]
Stickers have been ordered and I'm checking that off the list.

**Comment by lynnaloo** [comment]
@aproaps might be able to weigh in on this re: ODU's print center

**Comment by aproaps** [comment]
Yep I can print different sizes of color posters for us at ODU. The human factors grad student chapter would probably sponsor them for us so they'd be free. If not they're super cheap.

**Comment by aproaps** [comment]
(I'll add this to my to do list. Once we have designs I can just email the graphics department. And I'll talk to tech student group about sponsorship in the first meeting in January.)

**Comment by erikpmp** [comment]
We're going to close this and create individual issues as needed.
