### ISSUE TITLE
Save the Date Emails

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Organization#19]
- 757devcon mailing list
- MADExpo mailing list
- Slack email dump(s)
- Etc

Need to have the splash page #12 done first.

**Comment by 1kevgriff** [comment]
Draft in slack-channel.  Will arrange to send on Monday.

**Comment by 1kevgriff** [comment]
757devcon... sent
MADExpo... sent

**Comment by erikpmp** [comment]
I think `Slack email dump(s)` is the only thing left, and that's covered by #20, so I'm going to close this.
