### ISSUE TITLE
Personally reach out to 757dev Slack

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Organization#20]
- [x] Change 757DevCon channel w/in the 757Dev Slack.
- [x] Get the email addresses for everyone in the 757Dev Slack.
- [ ] Email each of the 757Dev members, or add them to our mailing list.

**Comment by lynnaloo** [comment]
@erikpmp I think we can close this?

**Comment by erikpmp** [comment]
@1kevgriff has talked about doing a direct email folks in the 757Dev slack. Kevin - that still the plan?

**Comment by erikpmp** [comment]
@1kevgriff you still going to do the email thing?

**Comment by erikpmp** [comment]
emails sent by @1kevgriff a couple of days ago.
