### ISSUE TITLE
Pick, notify and get committment from speakers

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Organization#30]
- [x] Notify Speakers
- [x] Send Rejection Emails
- [ ] Book Travel (if necessary)

**Voting Process**

* Use a Google Sheet.
* One column for each advisor to indicate they want the sessions included in RC.
* Each adviser gets 100 votes to use as they please. They could use 1 per session for 100 session, or 20 votes for 5 sessions. But each adviser uses 100 votes total.
* Add a comment column too for anyone to use if needed.
* We find the top 28 sessions.
* Discuss at the 2/16/2016 Hangout and make final decisions. Need 28 sessions + 10 alternates.
* Notify selected speakers and give them 3 days (NLT Friday 2/19/2016) to back out if needed.

**Comment by erikpmp** [comment]
done
