### ISSUE TITLE
Order T-Shirts

### ISSUE THREAD

**Issue by 1kevgriff** [RevolutionConf/Organization#33]
Staff/Volunteer Polos (nice shirts)
Attendee (not as awesome)

**Comment by lynnaloo** [comment]
@metaskills - I'm assuming Custom Ink is probably the way to go with these. 

I won't wear a polo, but agree with "nice"

**Comment by metaskills** [comment]
Yup... I can handle this. First, I will admit that the JSConf 2013 or was it 2012 CustomInk polos were really nice. I think it played with into the local golf scene too, which Virginia Beach does have and is DOUBLING DOWN (http://topgolf.com/us/virginia-beach/) on too. See here:

http://www.customink.com/categories/performance-polos/158/styles

The "Sport-Tek Heather Performance Polo" in red looks neat. I'll do a poll with my co-workers on what is hot and different in t-shirts and other things and get back here. In the mean time, can someone email me a logo? Original vector artwork would be nice. Thanks!

**Comment by metaskills** [comment]
So tri-blends t-shirts are hot.

* Canvas Tri-Blend - http://www.customink.com/styles/canvas-tri-blend-t-shirt/242000
* American Apparel Tri-Blend - http://www.customink.com/styles/american-apparel-tri-blend-t-shirt/169900
* American Apparel Tri-Blend Pocket - http://www.customink.com/styles/american-apparel-tri-blend-pocket-t-shirt/186400

A lot of us at CustomInk have been exploring tri-blend hoodies for our events and conferences too. We have been using the h

* Next Level Tri-Blend Long Sleeve - http://www.customink.com/styles/next-level-tri-blend-long-sleeve-hoodie/198000

Here are some images from the Ruby for Good event of that hoodie.

* https://pbs.twimg.com/media/CLWaaeFWoAAcuO8.jpg
* https://www.filepicker.io/api/file/0kgqhEeRHuJs3Cwcks2m
* https://pbs.twimg.com/media/CLWaYQFWwAEJ1Yh.jpg

If we pick something, I can start working up quotes and maybe even a CustomInk sponsorship.

**Comment by erikpmp** [comment]
Hey @metaskills...I think we defer to your opinion on shirts. Can you pick out the t-shirt that you think is best and provide pricing so I can plug that into the budget? Thanks. /cc @lynnaloo

**Comment by erikpmp** [comment]
Howdy @metaskills. I'm just checking in on t-shirts. Let us know if Custom Ink will be helping out, otherwise I have a local t-shirt vendor that can help us out.

**Comment by metaskills** [comment]
I can do it! Sorry, been in meetings a lot lately. I can share later. But yes, I can do this.

**Comment by erikpmp** [comment]
How are we coming along on t-shirts @metaskills ?

**Comment by metaskills** [comment]
I have, posted in Slack too.

### Next Level Tri-Blend Long Sleeve Hoodie

* Catalog: http://www.customink.com/styles/next-level-tri-blend-long-sleeve-hoodie/198000
* Design/Quote: http://www.customink.com/lab?cid=djn0-00ae-un61

### American Apparel Tri-Blend T-shirt

* Catalog: http://www.customink.com/styles/american-apparel-tri-blend-t-shirt/169900
* Design/Quote: http://www.customink.com/lab?cid=djn0-00ae-un87

**Comment by erikpmp** [comment]
dup of #123. closing...
