### ISSUE TITLE
Plan the Day of Event agenda

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#39]
When is the keynote, sessions, lunch, happy hour, etc? Someone needs to lay this all out. 

A similar issue, #61, is to actually make the agenda available to attendees by print or digital means, or both.

**Comment by lynnaloo** [comment]
Is this just for staff, or a repeat of the schedule issue?

**Comment by erikpmp** [comment]
It's probably a dup of #61. But since we have these two issues already, let's use this one as the task to plan out the day, and #39 for creating the print and digital materials for letting stakeholders know of the agenda. I'll update the issue to reflect that.

**Comment by erikpmp** [comment]
this is done
