### ISSUE TITLE
Order Nametags

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#40]
* [ ] lanyards & plastic sleeves
* [ ] design nametag layout (ex: w/ schedule on the back)
* [ ] identify a print solution

**Comment by lynnaloo** [comment]
This is the company that JSConf uses: https://www.accesseventsolutions.com/conferences

**Comment by lynnaloo** [comment]
I'll get some quotes on some different name tags from cheap to fancy.

**Comment by lynnaloo** [comment]
This is probably the fanciest option: https://www.accesseventsolutions.com/standard-matrix-laminates. It is $600 for 250 2-side lanyards. The benefit here is that we could put a schedule and a sponsoring company logo on the back. The one-sided version is $470.

This is a smaller version of the one above: https://www.accesseventsolutions.com/mini-laminates 250 @ $553.

The cheapest way to do it is to print our own two-sided badges (or do Kinko's) and put them in badge holders. This is probably the way to go if we don't have a company sponsoring badges.

**Comment by lynnaloo** [comment]
Re-assigning to @aproaps for ordering/design

**Comment by fvcproductions** [comment]
Just wanted to list this as a resource: https://www.conferencebadge.com --> it's $0.25 per badge if you print it yourself or $2.00/badge and they print them out and ship it to you

**Comment by lynnaloo** [comment]
We budgeted for some really nice nice badges, so I think Access does the cheapest "fancy" solutions, but if we run out of money then that's the backup plan.

**Comment by aproaps** [comment]
Haven't found anything nicer than the Access badges Linda already posted.

**Comment by aproaps** [comment]
They charge $1625.50 for 250 plain black lanyards.

**Comment by erikpmp** [comment]
ugh...that's pricey. I think Zack has a ton of leftovers from previous events. they'll have someone's name on them, but they'll be free. I'll check.

**Comment by 1kevgriff** [comment]
I have a bunch too.  Lemme check.

On Monday, March 28, 2016, Erik Olson <notifications@github.com> wrote:

> ugh...that's pricey. I think Zack has a ton of leftovers from previous
> events. they'll have someone's name on them, but they'll be free. I'll
> check.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/RevolutionConf/Organization/issues/40#issuecomment-202563736>
>


-- 
*Kevin Griffin*
Consultant, Griffin Consulting, Inc
(757) 447-4682 (Google voice)
Skype: kevgriffin83

I am available for short and long term software consulting opportunities.
It would be my pleasure to work with you and your organization.

http://www.kevgriffin.com :: http://www.twitter.com/1kevgriff

**Comment by lynnaloo** [comment]
The prices I posted above are what I got when I looked at that site. I'll double-check and see where the delta is. 

I thought we budged at least $600 for name tags? They don't have to be that nice if we're trying to save money here, but using Zack's leftover badges seems really low-budget for what we're trying to do here.

**Comment by lynnaloo** [comment]
Alibaba to the rescue :ship:

**Comment by aproaps** [comment]
LOL sorry about the typo above! 250 black cords are 160.25.

**Comment by erikpmp** [comment]
Ah...much better! @lynnaloo I was referring only to the lanyards, not the name tags themselves.

**Comment by lynnaloo** [comment]
Total misunderstanding all around. I was picturing "~~StartNorfolk 3~~ Rev Conf" lol

**Comment by erikpmp** [comment]
1. Do we still need lanyards? If so, I'll finalize that with Hatch
2. Are we all set with the plan to order name tags? Do we have to design the name tag or will the vendor/site do that for us?

**Comment by aproaps** [comment]
Re: lanyards, it's up to the group. We can get the plain black lanyards through the website. So if we did that the one sided larger nametags and lanyards would total $630.25 ($160.25 + $ 470).

**Comment by aproaps** [comment]
We also found some cheaper on a different site. They are $0.10 a piece plus shipping and take a week. I can order those today instead. Let me know.

**Comment by erikpmp** [comment]
I say go with the cheapest

**Comment by lynnaloo** [comment]
We went with the el-cheapo red lanyards that @aproaps found and they'll arrive in about 6 days. Working on graphic design for the name tags now.

**Comment by aproaps** [comment]
The nametags are ordered. Will post when they ship.

**Comment by erikpmp** [comment]
Great. I'm going to close. If you really want to keep this open then you can reopen.
