### ISSUE TITLE
Contract AV

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#41]
* Identify needs. What room needs what AV?
* Hire an AV company

**Comment by lynnaloo** [comment]
We'll probably want to hire someone to video the talks and possible also do a slide capture from the speaker.

**Comment by erikpmp** [comment]
Elite Presentations was the company that provided great AV for the conference in Oct that I attended at the VBRH. I sent them an email this morning with details and the date. I also asked if they provided augmented WIFI. I'll let you know when I get a quote.

**Comment by erikpmp** [comment]
done
