### ISSUE TITLE
Reach out to the media

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#43]
* [x] Reach out to Inside Business to announce
* [ ] Reach out to Tidewater Biz to announce
* [ ] Ask Inside Business to send a journalist
* [ ] Contact AltDaily

**Comment by lynnaloo** [comment]
We did a press release for NodeBotsDay both years and I should still have all of the contacts it went out to.

**Comment by erikpmp** [comment]
I sent my article to Inside Business. They declined to publish it stating it was too promotional.

**Comment by erikpmp** [comment]
Deany has reached out to Inside Business and they'll likely do an article, but not until the date gets closer. I asked her to post the event on the calendars of VA Pilot, Inside Biz, and Tidewater Biz. She is doing that. No need to keep this open now. Closing...
