### ISSUE TITLE
Create day of event schedule

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#61]
#39 is to plan out the day of the event. With that done, this task is to make the agenda available to attendees by either print or digital means, or both.

* [ ] Determine if we'll print or go digital or both
* [ ] Make it so

**Comment by lynnaloo** [comment]
We probably want to see if we can get ODU to print a poster with the event schedule closer to the event. As @iambriansreed indicated, it's a good idea to have some printed schedules. @aproaps was able to get some really nice posters printed for NodeBotsDay.

**Comment by erikpmp** [comment]
this is done
