### ISSUE TITLE
Form Keynote Search group

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#62]
Identify which advisors will participate in brainstorming for a keynote speaker.

Ideas
- Randall Monroe
- Sadi Metz
- Corey Haines
- Andy Hunt

**Comment by erikpmp** [comment]
Those who already expressed interested:
* @lynnaloo 
* @metaskills 
* @switchspan 
* @seanmerron

**Comment by lynnaloo** [comment]
I will go down the path to see how much Randall Monroe would cost and it's feasible before we make the decision.

**Comment by metaskills** [comment]
I will email Andy Hunt to see how he is doing.

**Comment by metaskills** [comment]
So Andy is amendable. Would love to explore more and scope our options.

**Comment by switchspan** [comment]
@metaskills - That is great! Why not spitball some names and see who to contact.
What do you an @lynnaloo think of Corey Haines? Possible? Not possible?

**Comment by metaskills** [comment]
Cant remember a Corey Haines talk. I've always been really partial to Sandi Metz. Her talks have been amazingly abstract and on target for our industry abroad. Thoughts?

**Comment by metaskills** [comment]
http://www.sandimetz.com

**Comment by lynnaloo** [comment]
I don't know Corey or Sandi. My only thoughts there are that their talks seem pretty Ruby-focused.

**Comment by metaskills** [comment]
Sandi's talks are amazing. I can't remember the last time they were about Ruby. 

* https://www.youtube.com/watch?v=JOM5_V5jLAs

Most are abstract about our industry. There is no code.

**Comment by lynnaloo** [comment]
Since we're spitballing, he's a totally non-developer but nerdy one: http://www.lelandmelvin.com

I'll add all of the ones we've discussed at the top.

**Comment by lynnaloo** [comment]
Sara Chipps is JavaScripter/robots person, but she's the founder of GirlDevelopIt, FlatIron School, and now Jewelbots. SaraJChipps.com

**Comment by switchspan** [comment]
@lynnaloo I like all three of those. :)

**Comment by switchspan** [comment]
@lynnaloo , @metaskills , and @guillermoandrae -> So here is what we have for a short list based on this forum and today's google hangout:

1) Randall Munroe (@lynnaloo investigating)
2) Leland Melvin (@lynaloo investigating)
3) Sara Chipps
4) Andy Hunt (@metaskills confirmed available)
5) Sandi Metz
6) Gina Trapani (@guillermoandrae investigating)
7) Corey Haines (@switchspan investigating)

**Comment by erikpmp** [comment]
I think this task - forming the keynote search committee - is done. The group is:
* Linda @lynnaloo
* Ken Collins @metaskills
* Ken Taylor @switchspan
* Sean Merron @seanmerron 

Issue #17 is Invite Keynote Speaker, and I recommend you move the comments about potential speakers to that issue. I'm closing this...
