### ISSUE TITLE
Volunteer/Staff tasks (Setup/Event/Tear Down)

### ISSUE THREAD

**Issue by lynnaloo** [RevolutionConf/Organization#70]
Create a Google Spreadsheet and/or Sign-up Genius for tasking volunteers and staff for specific tasks for the day of the event.

**Comment by fvcproductions** [comment]
I can help with this also: Typeform already has an awesome sign-up form set up: http://www.typeform.com/examples/forms/volunteer-application-form-template/

**Comment by erikpmp** [comment]
Here are the spots that we need for volunteers.

![screen shot 2016-01-26 at 5 54 02 pm](https://cloud.githubusercontent.com/assets/1593872/12598008/cf689e3c-c455-11e5-8731-6cbd6172f5fe.png)

**Comment by fvcproductions** [comment]
Alright so should I get started on creating a system to recruit these volunteers?

**Comment by erikpmp** [comment]
With there being only 12 total volunteers, I think just asking ppl in our group who will take which shifts should be good enough.

**Comment by fvcproductions** [comment]
Oh okay in that case, making that into a Google Sheet that can be edited amongst the team would be ideal

**Comment by fvcproductions** [comment]
I'm having to do that if it's not already in Google Sheets (you can email me the CSV/excel file)

**Comment by erikpmp** [comment]
Within the `RevConf Advisors` folder in Google Drive, I created a Sheet that any of the volunteers can edit to fill in which assignments they'd like to take.

**Comment by erikpmp** [comment]
I emailed the team (advisors and volunteers) a reminder to fill in when they can volunteer.

**Comment by erikpmp** [comment]
Reminded advisors that we need the last few TBDs filled in, and asked them to sign up. If they don't soon then I'll make assignments.

![screen shot 2016-05-04 at 4 57 52 pm](https://cloud.githubusercontent.com/assets/1593872/15029015/a4d08204-1219-11e6-89cc-e3f9ae5800d0.png)

**Comment by erikpmp** [comment]
All assignments filled.

![screen shot 2016-05-04 at 5 15 59 pm](https://cloud.githubusercontent.com/assets/1593872/15029536/fec88b60-121b-11e6-86f0-1c67261da65e.png)
