### ISSUE TITLE
Create sign-up page for Slack Room

### ISSUE THREAD

**Issue by lynnaloo** [RevolutionConf/Organization#71]
We can use Bret's sign-up page, or there's another open-source app we can setup.

**Comment by 1kevgriff** [comment]
Are we making the Slack public or just for attendees?  I think it might be easier/better for private channel to do mass invites by hand.

**Comment by lynnaloo** [comment]
We can rename this one, "enter attendees in Slack Room as they register" :grin:

**Comment by erikpmp** [comment]
I think we can close this and instead this just needs to be on our checklist of things to do (invite them to slack) when someone registers.
