### ISSUE TITLE
Reach out to regional groups: Rails/Ruby 

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#72]
Identify user groups and meetups in the below markets. Email the organizer directly and let him/her know what we're doing. Share the URL to our website and ask them to distribute it to their membership.

Offer to send stickers, posters and handouts. Ask how many typically attend and where you should mail the stuff to. Add a GitHub issue assigned to @erikpmp to send stickers and rack cards to the organizer (provider his/her name and the average number of attendees).

* Hampton Roads
* Charlotte
* Maryland
* Roanoke
* Raleigh
* DC
* Richmond
* Williamsburg
* OBX
* Eastern Shore

**Comment by metaskills** [comment]
OK, I'll take this one on!

**Comment by erikpmp** [comment]
I think this done enough for now.

**Comment by metaskills** [comment]
Agreed. We have even been talking about it in slack at work. I'll drop another note in DC Tech today.
