### ISSUE TITLE
Reach out to regional groups: .NET

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#73]
Identify user groups and meetups in the below markets. Email the organizer directly and let him/her know what we're doing. Share the URL to our website and ask them to distribute it to their membership.

Offer to send stickers, posters and handouts. Ask how many typically attend and where you should mail the stuff to. Add a GitHub issue assigned to @erikpmp to send stickers and rack cards to the organizer (provider his/her name and the average number of attendees).

* Hampton Roads
* Charlotte
* Maryland
* Roanoke
* Raleigh
* DC
* Richmond
* Williamsburg
* OBX
* Eastern Shore

**Comment by 1kevgriff** [comment]
- [ ] HRNUG
- [ ] Richmond .NET
- [ ] Roanoke Valley .NET
- [ ] Cap Area .NET
- [ ] DC .NET
- [ ] TriNUG
- [ ] CMAP (Maryland)

**Comment by 1kevgriff** [comment]
Emailed all VA/MD/NC user groups.

**Comment by erikpmp** [comment]
I think this done enough for now.
