### ISSUE TITLE
Reach out to regional groups: JS

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#74]
Identify user groups and meetups in the below markets. Email the organizer directly and let him/her know what we're doing. Share the URL to our website and ask them to distribute it to their membership.

Offer to send stickers, posters and handouts. Ask how many typically attend and where you should mail the stuff to. Add a GitHub issue assigned to @erikpmp to send stickers and rack cards to the organizer (provider his/her name and the average number of attendees).

* Hampton Roads
* Charlotte
* Maryland
* Roanoke
* Raleigh
* DC
* Richmond
* Williamsburg
* OBX
* Eastern Shore

**Comment by lynnaloo** [comment]
I reached out to various groups in the categories above and any organizers that I knew from NodeBots or other Slack channels. I have some addresses for stickers (and rack cards once we print them). It's not specifically JS, but I'll reach out to the Williamsburg group as well.
