### ISSUE TITLE
Reach out to regional groups: UI/UX

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#75]
Identify user groups and meetups in the below markets. Email the organizer directly and let him/her know what we're doing. Share the URL to our website and ask them to distribute it to their membership.

Offer to send stickers, posters and handouts. Ask how many typically attend and where you should mail the stuff to. Add a GitHub issue assigned to @erikpmp to send stickers and rack cards to the organizer (provider his/her name and the average number of attendees).

* Hampton Roads
* Charlotte
* Maryland
* Roanoke
* Raleigh
* DC
* Richmond
* Williamsburg
* OBX
* Eastern Shore

**Comment by aproaps** [comment]
Emails sent:
Charlotte UX meetup 
Tricities UXPA 
DC UXPA 
NOVA UX meetup
Richmond UX user group
Charlottesville UX meetup
Baltimore UX meetup

Also contacted all the above via Twitter.

**Comment by aproaps** [comment]
@erikpmp  A couple Richmond and NOVA groups have replied. They're posting the event info  to their message boards and announcing it in their first meeting. 

Richmond said they'd take some swap to pass out (about 30 people at events). Contact info:

Mark Badger
CapTech Consulting
7100 Forest Avenue, 2nd Floor
Richmond, VA 23226

**Comment by erikpmp** [comment]
I will get this out by the end of the week.

**Comment by erikpmp** [comment]
@aproaps Reassigned to me to send out the stickers. But pls continue to contact other user groups if there are others to be contacted.

**Comment by erikpmp** [comment]
The stickers are in the mail. Closing...
