### ISSUE TITLE
Reach out to regional groups: Google Developers

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#76]
Identify user groups and meetups in the below markets. Email the organizer directly and let him/her know what we're doing. Share the URL to our website and ask them to distribute it to their membership.

Offer to send stickers, posters and handouts. Ask how many typically attend and where you should mail the stuff to. Add a GitHub issue assigned to @erikpmp to send stickers and rack cards to the organizer (provider his/her name and the average number of attendees).

* Hampton Roads
* Charlotte
* Maryland
* Roanoke
* Raleigh
* DC
* Richmond
* Williamsburg
* OBX
* Eastern Shore

**Comment by switchspan** [comment]
Emailed Nitya Narasimhan and Chida Sadayappan (Google Developers North East Region Mentors) with details on the signup and call for speakers. Requested that they pass on the info to the NE region group organizers.

**Comment by erikpmp** [comment]
I think this done enough for now.
