### ISSUE TITLE
Reach out to regional groups: PhP

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#77]
Identify user groups and meetups in the below markets. Email the organizer directly and let him/her know what we're doing. Share the URL to our website and ask them to distribute it to their membership.

Offer to send stickers, posters and handouts. Ask how many typically attend and where you should mail the stuff to. Add a GitHub issue assigned to @erikpmp to send stickers and rack cards to the organizer (provider his/her name and the average number of attendees).

* Hampton Roads
* Charlotte
* Maryland
* Roanoke
* Raleigh
* DC
* Richmond
* Williamsburg
* OBX
* Eastern Shore

**Comment by guillermoandrae** [comment]
I can help out here.

**Comment by erikpmp** [comment]
@guillermoandrae Great. @JeffMatson is pretty tight with the WordPress community. We may want to split this up into one issue for PhP and another for WordPress. Thoughts?

**Comment by guillermoandrae** [comment]
Splitting it up sounds fine to me.


--

Guillermo A. Fisher

*w.* http://guillermoandraefisher.com
*e.* me@guillermoandraefisher.com
*p*. +1 757 450 8819

**Comment by erikpmp** [comment]
will do

**Comment by erikpmp** [comment]
I think this done enough for now.
