### ISSUE TITLE
Reach out to regional groups: Universities

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#79]
Identify user groups and meetups in the below markets. Email the organizer directly and let him/her know what we're doing. Share the URL to our website and ask them to distribute it to their membership.

Offer to send stickers, posters and handouts. Ask how many typically attend and where you should mail the stuff to. 

Ask Erik, Linda or Kevin to send stickers (1x the ave # attendees), 1 poster, and 4x9 rack cards (1x the ave # of attendees).

* Hampton Roads
* Charlotte
* Maryland
* Roanoke
* Raleigh
* DC
* Richmond
* Williamsburg
* OBX
* Eastern Shore

**Comment by fvcproductions** [comment]
I can help out with this also - at least with Hampton University and the VA ACM Slack (already posted in announcements). 

The Slack channel has a bunch of different schools as members (ODU, Hampton University, CNU, VCU, George Mason, W&M) already so hopefully I can gain some traction there.

**Comment by erikpmp** [comment]
I think this done enough for now.
