### ISSUE TITLE
Send the stickers

### ISSUE THREAD

**Issue by switchspan** [RevolutionConf/Organization#84]
@erikpmp 

Can I get some revolution conf stickers for our next GDG meeting?

-Ken

**Comment by erikpmp** [comment]
You betcha! When is the meeting? We'll need to arrange a hand off meeting beforehand. I'll be in Norfolk tomorrow, and on Wed VB in the morning and Norfolk in the afternoon.

**Comment by switchspan** [comment]
The meeting is next Thursday.

**Comment by erikpmp** [comment]
this is done
