### ISSUE TITLE
Create sponsor prospectus

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#85]
Using the matrix attached to this issue, create a good looking prospectus / flyer / PDF that we can email to potential sponsors and eventually have for download on our website. 

(spreadsheet provided via Slack)

**Comment by lynnaloo** [comment]
@erikpmp @1kevgriff I think we need to make a few more tweaks to the attached sponsor matrix before it goes live.

**Comment by erikpmp** [comment]
Done. 

[RevolutionConfSponsorPackage-reduce.pdf](https://github.com/RevolutionConf/Organization/files/117701/RevolutionConfSponsorPackage-reduce.pdf)
