### ISSUE TITLE
Contract WIFI

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#87]
We'll need supplementary WIFI for the venue

**Comment by switchspan** [comment]
Did we figure out who we will reach out to for this?

**Comment by erikpmp** [comment]
We are going to get 12 cellular access points from Elite Presentations. I called and emailed them (Tiffani) just now. During the call she confirmed that we are good to go and we should not be required to take any further action unless she gets back to me. Closing!!!
