### ISSUE TITLE
Buy goodie bags (the actual bag that swag will go in)

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/Organization#88]

**Comment by lynnaloo** [comment]
Assigning to @aproaps to either find a cheap option or a sponsor

**Comment by aproaps** [comment]
Been working on a spreadsheet bag prices (in RevConf Drive). I have a couple more companies to add, but I've used all three of these before for various events. Anything nicer than poly or basic cotton is too pricey for 250 bags so I haven't included them. [](https://docs.google.com/spreadsheets/d/1Oxn6X-KLepT39FuT94n76RxkO6SDuRL-Dg5bWt8gZrc/edit?usp=sharing )

**Comment by aproaps** [comment]
Is there a bag size/fabric that you all think is ideal from the spreadsheet I put together? I haven't added more choices because I haven't found anything cheaper yet. But I want to make sure I'm on the right track with what we're looking for within the budget.

**Comment by lynnaloo** [comment]
I added a line-item to the budget for $250 and I think I'm fine with either of the $225/$250 choices. @erikpmp @1kevgriff If you agree, we could go ahead and order these and have one less thing to worry about a week out.

**Comment by erikpmp** [comment]
Go for it!

**Comment by erikpmp** [comment]
I'm going to close this because UXPA is taking care of this. So from a RevConf perspective, this has been addressed and we no longer need to track this.
